#!/usr/bin/env bash

cd /fp/projects01/ec29/bthj/kromosynth-cli/cli-app

apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/switch-both.jsonc --analysis-operations diversity-from-embeddings --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-both
apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/switch-features.jsonc --analysis-operations diversity-from-embeddings --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-features
apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/switch-fitness.jsonc --analysis-operations diversity-from-embeddings --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-fitness
apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/switch-train.jsonc --analysis-operations diversity-from-embeddings --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-train
apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/non-oee_guitar.jsonc --analysis-operations diversity-from-embeddings --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/non/guitar
apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/non-oee_mallet.jsonc --analysis-operations diversity-from-embeddings --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/non/mallet
apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/non-oee_reed.jsonc --analysis-operations diversity-from-embeddings --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/non/reed