#!/usr/bin/env bash

cd /fp/projects01/ec29/bthj/kromosynth-cli/cli-app

# apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/switch-both.jsonc --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-both
# apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/switch-features.jsonc --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-features
# apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/switch-fitness.jsonc --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-fitness
# apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/switch-train.jsonc --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-train
# apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/non-oee_guitar.jsonc --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/non/guitar
# apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/non-oee_mallet.jsonc --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/non/mallet
# apptainer exec --nv --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/non-oee_reed.jsonc --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/non/reed

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/OEE/switch-features_x100_customRef.jsonc --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-features/100x-customRef

apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/switch-both.jsonc --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-both
apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/switch-features.jsonc --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-features
apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/switch-fitness.jsonc --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-fitness
apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/switch-train.jsonc --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-train
apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/non-oee_guitar.jsonc --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/non/guitar
apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/non-oee_mallet.jsonc --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/non/mallet
apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/tempOEE/non-oee_reed.jsonc --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/non/reed

apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/OEE/switch-features_x100_customRef.jsonc --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-features/100x-customRef

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/OEE/switch-features_x100_customRef_oneCPPNPerFreq.jsonc --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-features/100x-customRef_oneCPPNPerFreq
apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/OEE/switch-features_x100_customRef_oneCPPNPerFreq.jsonc --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/oee/switch-features/100x-customRef_oneCPPNPerFreq






# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_classDims_clsscSynth.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_classDims_clsscSynth
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_classDims.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_classDims
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_durDims.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_durDims
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_x100.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_x100
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-7-moods_parents-max-1.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-7-moods_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-7-moods_parents-max-10.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-7-moods_parents-max-10
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-acoustic_parents-max-1.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-acoustic_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-aggressive_parents-max-1.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-aggressive_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-electronic_parents-max-1_noRamp.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-electronic_parents-max-1_noRamp
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-electronic_parents-max-1_ramp.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-electronic_parents-max-1_ramp
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-happy_parents-max-1.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-happy_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-happy_parents-max-10.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-happy_parents-max-10
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-party_parents-max-1.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-party_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-relaxed_parents-max-1.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-relaxed_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-sad_parents-max-1.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-sad_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-moodDims_parents-max-1.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-moodDims_parents-max-1

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/problems/evolution-runs_mfcc_pca-quantised_quality-problems_parents-max-1_energyScaled_clsscSynth.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/problems/evolution-runs_mfcc_pca-quantised_quality-problems_parents-max-1_energyScaled
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/problems/evolution-runs_mfcc_pca-quantised_quality-problems_parents-max-1_energyScaled.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/problems/evolution-runs_mfcc_pca-quantised_quality-problems_parents-max-1_energyScaled_clsscSynth

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_clsscSynth.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_clsscSynth
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_rghnssScldByLdnss.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_rghnssScldByLdnss
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_rghnssScldByLdnss_clsscSynth.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_rghnssScldByLdnss_clsscSynth
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-10.jsonc  --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-10


# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_classDims_clsscSynth.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_classDims_clsscSynth
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_classDims.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_classDims
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_durDims.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_durDims
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_x100.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_x100
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-7-moods_parents-max-1.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-7-moods_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-7-moods_parents-max-10.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-7-moods_parents-max-10
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-acoustic_parents-max-1.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-acoustic_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-aggressive_parents-max-1.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-aggressive_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-electronic_parents-max-1_noRamp.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-electronic_parents-max-1_noRamp
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-electronic_parents-max-1_ramp.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-electronic_parents-max-1_ramp
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-happy_parents-max-1.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-happy_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-happy_parents-max-10.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-happy_parents-max-10
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-party_parents-max-1.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-party_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-relaxed_parents-max-1.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-relaxed_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-sad_parents-max-1.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-mood-sad_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-moodDims_parents-max-1.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/moods/evolution-runs_mfcc_pca-quantised_quality-moodDims_parents-max-1

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/problems/evolution-runs_mfcc_pca-quantised_quality-problems_parents-max-1_energyScaled_clsscSynth.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/problems/evolution-runs_mfcc_pca-quantised_quality-problems_parents-max-1_energyScaled
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/problems/evolution-runs_mfcc_pca-quantised_quality-problems_parents-max-1_energyScaled.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/problems/evolution-runs_mfcc_pca-quantised_quality-problems_parents-max-1_energyScaled_clsscSynth

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_clsscSynth.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_clsscSynth
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_rghnssScldByLdnss.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_rghnssScldByLdnss
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_rghnssScldByLdnss_clsscSynth.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_rghnssScldByLdnss_clsscSynth
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file  /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-10.jsonc  --analysis-operations score-matrix --step-size 1 --write-to-folder /fp/projects01/ec29/bthj/QD/analysis/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-10


# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-analysis --evolution-runs-config-json-file    --analysis-operations qd-scores,coverage,new-elite-count --step-size 1 --write-to-folder 

