#!/usr/bin/env bash

cd /fp/projects01/ec29/bthj/kromosynth-cli/cli-app

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_0.5s_a.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_0.5s_b.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_0.5s_c.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_0.5s_d.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_0.5s_e.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_0.5s_f.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_0.5s_g.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_0.5s_h.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_0.5s_i.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_0.5s_j.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_10s_a.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_10s_b.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_10s_c.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_10s_d.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb/evolution-runs_10s_e.jsonc


# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_0.5s_a.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_0.5s_b.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_0.5s_c.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_0.5s_d.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_0.5s_e.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_0.5s_f.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_0.5s_g.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_0.5s_h.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_0.5s_i.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_0.5s_j.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_10s_a.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_10s_b.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_10s_c.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_10s_d.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-CPPN_only/evolution-runs_10s_e.jsonc



# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_0.5s_a.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_0.5s_b.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_0.5s_c.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_0.5s_d.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_0.5s_e.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_0.5s_f.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_0.5s_g.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_0.5s_h.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_0.5s_i.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_0.5s_j.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_0.5s_a_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_0.5s_b_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_0.5s_c_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_0.5s_d_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_0.5s_e_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_0.5s_f_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_0.5s_g_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_0.5s_h_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_0.5s_i_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_0.5s_j_in_fact_with_noise.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_10s_a.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_10s_b.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_10s_c.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_10s_d.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_10s_e.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_10s_f.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_10s_g.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_10s_h.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_10s_i.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/evolution-runs_10s_j.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_10s_a_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_10s_b_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_10s_c_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_10s_d_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_10s_e_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_10s_f_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_10s_g_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_10s_h_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_10s_i_in_fact_with_noise.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-noNoise/runs-in-fact-with-noise-nodes/evolution-runs_10s_j_in_fact_with_noise.jsonc



# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-single-class/evolution-runs-a.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-single-class/evolution-runs-b.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-single-class/evolution-runs-c.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-single-class/evolution-runs-d.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-single-class/evolution-runs-e.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-single-class/evolution-runs-f.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-single-class/evolution-runs-g.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-single-class/evolution-runs-h.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-single-class/evolution-runs-i.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-single-class/evolution-runs-j.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_0.5s_a.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_0.5s_b.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_0.5s_c.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_0.5s_d.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_0.5s_e.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_0.5s_f.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_0.5s_g.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_0.5s_h.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_0.5s_i.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_0.5s_j.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_10s_a.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_10s_b.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_10s_c.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_10s_d.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-one_comb-singleCellWin/evolution-runs_10s_e.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-classScoringVariationsAsContainerDimensions/evolution-runs_a.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-classScoringVariationsAsContainerDimensions/evolution-runs_b.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-classScoringVariationsAsContainerDimensions/evolution-runs_c.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-classScoringVariationsAsContainerDimensions/evolution-runs_d.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-classScoringVariationsAsContainerDimensions/evolution-runs_e.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-classScoringVariationsAsContainerDimensions/evolution-runs_f.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-classScoringVariationsAsContainerDimensions/evolution-runs_g.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-classScoringVariationsAsContainerDimensions/evolution-runs_h.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-classScoringVariationsAsContainerDimensions/evolution-runs_i.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/conf-classScoringVariationsAsContainerDimensions/evolution-runs_j.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-acoustic_parents-max-1.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-aggressive_parents-max-1.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-electronic_parents-max-1_noRamp.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-electronic_parents-max-1_ramp.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-happy_parents-max-1.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-party_parents-max-1.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-relaxed_parents-max-1.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-sad_parents-max-1.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-mood-happy_parents-max-10.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-7-moods_parents-max-1.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/moods/evolution-runs_mfcc_pca-quantised_quality-7-moods_parents-max-10.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_x100.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_classDims.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-10.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_clsscSynth.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_rghnssScldByLdnss_clsscSynth.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/psychoacoustic/evolution-runs_mfcc_pca-quantised_quality-psychoacoustic_parents-max-1_rghnssScldByLdnss.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/problems/evolution-runs_mfcc_pca-quantised_quality-problems_parents-max-1_energyScaled_clsscSynth.jsonc
# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/problems/evolution-runs_mfcc_pca-quantised_quality-problems_parents-max-1_energyScaled.jsonc

# apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_classDims_clsscSynth.jsonc

apptainer exec --mount 'type=bind,source=/fp/projects01,destination=/fp/projects01' /fp/projects01/ec29/bthj/kromosynth-runner-CPU.sif node kromosynth.js evo-runs-percent-completion --evolution-runs-config-json-file /fp/projects01/ec29/bthj/QD/unsupervised/runsconf/instrumentation/evolution-runs_mfcc_pca-quantised_quality-instrumentation_parents-max-1_durDims.jsonc
